name: Build Executables

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyserial pillow zwoasi numpy requests

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onedir --windowed --add-data "mega_monture:mega_monture" --add-data "teensy_monture:teensy_monture" --add-data "teensy_raquette:teensy_raquette" goto_andrivet_config_tool.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GotoAndrivetConfig_${{ matrix.os }}
        path: dist/goto_andrivet_config_tool
